### ISSUE TITLE
support node 10.4

### ISSUE THREAD

**Issue by benwaffle** [romgrk/node-gtk#19] opened 2018-06-12 14:58 UTC

**Comment by romgrk** [comment] 2018-06-12 15:41
Yes, currently only tested with 8.x.
Issues with 10.x are caused by the removal of V8's `object->ForceSet()`, which is still used in nan@2.10.
https://github.com/nodejs/nan/issues/763

**Comment by romgrk** [comment] 2018-06-12 20:32
https://github.com/nodejs/nan/issues/763#issuecomment-396651963
![screenshot from 2018-06-12 16-23-31](https://user-images.githubusercontent.com/1423607/41315264-fc1c7ab2-6e5c-11e8-89c0-49669b9343ae.png)

Which is true `#if NODE_MODULE_VERSION >= NODE_9_0_MODULE_VERSION`:
https://github.com/nodejs/nan/blob/master/nan_maybe_43_inl.h#L137-L144

Not sure where it's coming from yet. (Btw, I'm assuming you get the same issue I get on my home laptop when building, which is something related to `ForceSet`)

**Comment by benwaffle** [comment] 2018-06-12 20:34
```
../src/function.cc:59:58: error: too few arguments to function call, expected 4, have 3
    auto res = stringify->CallAsFunction(JSON, 1, args_js);
               ~~~~~~~~~~~~~~~~~~~~~~~~~                 ^
```

```
../node_modules/nan/nan_callbacks_12_inl.h:108:64: error: no member named 'Callee' in 'v8::FunctionCallbackInfo<v8::Value>'
  inline v8::Local<v8::Function> Callee() const { return info_.Callee(); }
                                                         ~~~~~ ^
```

**Comment by romgrk** [comment] 2018-06-12 22:01
0d789b9e0b56ffc88be8125ccd54e81becaf2dc3 will solve the top one.

Bottom one is probably related to invalid node or nan headers. Could you try to find which version of node and nan headers are used?
 - Nan: `cat node_modules/nan/package.json | grep '"version"'`
 - Node: search in `./build/node-gtk.target.mk` for `.node-gyp`, or list `~/.nody-gyp`

**Comment by romgrk** [comment] 2018-06-13 02:03
Could reproduce the issue, opened https://github.com/nodejs/nan/issues/788.

**Comment by romgrk** [comment] 2018-06-14 16:54
Basically, it seems that nan doesn't support node 10.x even though it says it does. The reason is that `FunctionCallbackInfo.Callee` has been deprecated & removed on V8, but nan didn't catch up.

For the moment, it's possible to build and run on node 10.x by commenting the line 108 of `node_modules/nan/nan_callbacks_12_inl.h`. We'll wait for a reply from nan's maintainer to check for a more permanent solution.

**Comment by romgrk** [comment] 2018-06-15 03:07
Waiting for a PR on the upstream nan to be merged, but this should now compile anyway (tested on 10.2.1). Does it work for you, @benwaffle?

**Comment by benwaffle** [comment] 2018-06-15 14:59
yep

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1713819/41474874-29a1bad0-708b-11e8-8b30-99d2554daf6e.png">

**Closed** 2018-06-15 14:59 UTC
Labels: 1.0
