### ISSUE TITLE
Passing number arrays to GLib.Bytes

### ISSUE THREAD

**Issue by docb** [romgrk/node-gtk#214] opened 2020-09-26 10:47 UTC
i wonder how to pass an number array to GLib.Bytes

in the tests an js array is passed to a GLib function -  ths works
but my attempt to pass an array with bytes to GLib.Bytes fails

 
```
  const dat = [ 104, 101, 108, 108, 111 ] // hello
  const result = GLib.base64Encode(dat, dat.length)
  console.log('Result:', result)

  const data = [ 1,4,6, ......];
  let pixBuf = GdkPixbuf.Pixbuf.newFromBytes(new GLib.Bytes(data),0,1,8,width,height,height*4);
```
 
output:

```
Result: aGVsbG8=

.../myfile.js:173
  let pixBuf = GdkPixbuf.Pixbuf.newFromBytes(new GLib.Bytes(data),0,1,8,width,height,height*4);
                                                                                                      
TypeError: Expected argument of type Number[] for parameter data, got '[object Array]'
```

May be there are some other ways to do this. The goal is to generate an image in memory and draw it on the background of a widget.

**Comment by docb** [comment] 2020-09-26 14:15
It seems to work with an Uint8Array.

**Comment by romgrk** [comment] 2020-10-02 18:54
Ok, cool! If you don't mind I'll keep open just to investigate, I would have expected that to work even with an Array.

**Comment by docb** [comment] 2020-10-04 01:13
ok, would it be possible to talk to you about some issues in this project? I really like it but i have serious problems (see the other issues)

**Comment by romgrk** [comment] 2020-10-17 03:57
Sorry for the delay. Sure, do you have any specific issue that's blocking you right now? I'll try to address the other issues as soon as I have time, let me know if I have missed one. If you need you can also contact me at `romgrk.cc` on `gmail.com`.

For the current issue, I've been able to make it run without problem, here is the code:
```js
/*
 * numbers-to-bytes.js
 */

const gi = require('.')
const GLib = gi.require('GLib', '2.0')
const GdkPixbuf = gi.require('GdkPixbuf')

const dat = [ 104, 101, 108, 108, 111 ] // hello
const result = GLib.base64Encode(dat, dat.length)
console.log('Result:', result)

const data =
  Array.from({ length: 2 }, (_, i) =>
    Array.from({ length: 5 }, (_, j) =>
      [255, 0, 0] // red
  ))
  .flat(2)

console.log(data)

const bytes = new GLib.Bytes(data)
console.log(bytes)

const width = 2
const height = 5

let pixBuf = GdkPixbuf.Pixbuf.newFromBytes(
  bytes,
  0, // colorspace
  false, // has_alpha
  8, // bits_per_sample
  width,
  height,
  height * 4
)
```

If for some reason it's still not working for you, attach a runnable example that reproduces your issue I'll take a look at it.

**Comment by romgrk** [comment] 2020-10-26 08:45
Closing as I can't reproduce the issue, be sure to include a runnable example if it still happens. Also you can message on http://gitter.im/romgrk if you need.

**Closed by romgrk** 2020-10-26 08:45 UTC
