### ISSUE TITLE
Missing GIR info for: GdkX11Screen

### ISSUE THREAD

**Issue by SpaceboyRoss01** [romgrk/node-gtk#84] opened 2018-11-08 02:10 UTC
```
gobject.cc: GetClassTemplate: 380: Assertion 'gi_info != NULL' failed: Missing GIR info for: GdkX11Screen
**
ERROR:../src/gobject.cc:380:Local<v8::FunctionTemplate> GNodeJS::GetClassTemplate(GIBaseInfo *, GType): code should not be reached
Aborted (core dumped)
```

**Comment by romgrk** [comment] 2018-11-08 03:35
Duplicate of #74, up-coming fix in #82.

Meanwhile, you can add the following line after your imports to solve it:
```js
gi.require('GdkX11')
```

**Closed by romgrk** 2018-11-08 03:35 UTC
