### ISSUE TITLE
Signal not found error

### ISSUE THREAD

**Issue by sessionm21** [romgrk/node-gtk#123] opened 2019-06-22 23:24 UTC
From the README.md
``` js
const win = new Gtk.Window();
win.on('destroy', () => Gtk.mainQuit())
win.on('delete-event', () => false)
```
If either ```destroy``` or ```delete-event``` are connected, the example will crash
``` bash
Error: Signal "� ��vent" not found for instance of Gtk.Window
    at GtkWindow.on (/home/user/Documents/ReactGtk/basic/node_modules/node-gtk/lib/index.js:54:32)
    at Object.<anonymous> (/home/user/Documents/ReactGtk/basic/App.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

package.json
``` js
{
  "name": "basic",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@react-gtk/binding": "^0.0.8",
    "react": "^16.8.4"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.0",
    "@babel/core": "^7.2.0",
    "@babel/node": "^7.2.0",
    "@babel/preset-react": "^7.0.0",
    "babel-preset-jam": "^0.1.0",
    "eslint": "^5.9.0",
    "eslint-config-jam": "^0.1.6",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "yo": "^2.0.5"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
OS :  Fedora release 29 (Twenty Nine)
Kernel : SELinux 4.20.0-rc7 ARMv7l
WM : i3
GCC : gcc (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
node : v10.15.3
npm : 6.4.1

**Comment by romgrk** [comment] 2019-06-23 01:25
Could you provide the full code you're using to reproduce the error?

**Comment by sessionm21** [comment] 2019-06-23 20:37
``` js
const gi = require('node-gtk')
Gtk = gi.require('Gtk', '3.0')

gi.startLoop()
Gtk.init()

const win = new Gtk.Window();
win.on('destroy', () => Gtk.mainQuit())
win.on('delete-event', () => false)

win.setDefaultSize(200, 80)
win.add(new Gtk.Label({ label: 'Hello Gtk+' }))

win.showAll();
Gtk.main();
```

**Comment by drom98** [comment] 2019-06-26 15:19
You're not declarating Gtk. You must assign it to a const or let variable.

**Comment by romgrk** [comment] 2019-06-27 02:00
I've been able to run that code succesfully with the latest version of `node-gtk` and node 10.0.0. Your `package.json` doesn't mention `node-gtk`, could you check again which version is installed?

**Comment by sessionm21** [comment] 2019-06-27 03:07
I was using 0.2.2 at the time, when I re-ran ```npm install --save node-gtk``` this time with --save it updated to 0.3.0. However it will still crash if either ```destroy``` or ```delete-event``` are connected to ```win```.
Here's a pastebin of the compile from source step : [https://pastebin.com/raw/mVcQy6Db](https://pastebin.com/raw/mVcQy6Db)
Here's the new ```package.json```
``` js
{
  "name": "basic",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "@react-gtk/binding": "^0.0.8",
    "node-gtk": "^0.3.0",
    "react": "^16.8.4"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.0",
    "@babel/core": "^7.2.0",
    "@babel/node": "^7.2.0",
    "@babel/preset-react": "^7.0.0",
    "babel-preset-jam": "^0.1.0",
    "eslint": "^5.9.0",
    "eslint-config-jam": "^0.1.6",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "yo": "^2.0.5"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
The error message looks about the same, I think:
``` bash
/home/user/Documents/ReactGtk/basic/node_modules/node-gtk/lib/index.js:54
        const handlerID = this.connect(event, callback)
                               ^

Error: Signal "��" not found for instance of Gtk.Window
    at GtkWindow.on (/home/user/Documents/ReactGtk/basic/node_modules/node-gtk/lib/index.js:54:32)
    at Object.<anonymous> (/home/user/Documents/ReactGtk/basic/App.js:8:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by romgrk** [comment] 2019-06-27 17:48
Ok, looks like you're on ARM. I've never ran any test in that environment, I will try to setup an ARM VM and check if I can reproduce the issue.

**Comment by marcocarnut** [comment] 2020-02-25 17:36
I found that simply moving the part that gets the `signal name` to be immediately before the call to `FindSignalInfo` solves this problem, as in the patch below:

```
--- node-gtk/src/gobject.cc.original	2020-02-25 17:29:37.818856368 +0000
+++ node-gtk/src/gobject.cc	2020-02-25 17:30:05.568774581 +0000
@@ -269,11 +269,11 @@
         return;
     }
 
-    const char *signal_name = *Nan::Utf8String (TO_STRING (info[0]));
     Local<Function> callback = info[1].As<Function>();
     GType gtype = (GType) TO_LONG (Nan::Get(info.This(), UTF8("__gtype__")).ToLocalChecked());
 
     GIBaseInfo *object_info = g_irepository_find_by_gtype (NULL, gtype);
+    const char *signal_name = *Nan::Utf8String (TO_STRING (info[0]));
     GISignalInfo *signal_info = FindSignalInfo (object_info, signal_name);
 
     if (signal_info == NULL) {
```

**Comment by romgrk** [comment] 2020-02-27 22:27
That's very strange :/ Maybe `g_irepository_find_by_gtype` is initializing something. I've applied the patch, let's see if it solves something. The fix will be in the next release.

**Comment by marcocarnut** [comment] 2020-02-27 22:32
Strange indeed. I think something is corrupting the stack. During compilation, tons of warnings are shown about mismatched method signatures.

**Comment by romgrk** [comment] 2020-04-18 13:31
Release `0.4` included many improvements, if the problem persists please re-open.

**Closed by romgrk** 2020-04-18 13:31 UTC
Labels: bug, need-feedback
